//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;

   // using Microsoft.EntityFrameworkCore;
    using System.Data.Entity.Infrastructure;
    
    public partial class Api_NutcacheEntities : DbContext
    {
        public Api_NutcacheEntities()
            : base("name=Api_NutcacheEntities")
        {
        }
    
        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
    }
}
